import type { GuestProfile } from "./guest-crm.types";

export type ManualAirbnbReservation = { id: string; organizationId: string; guestName: string; phone: string; checkIn: string; checkOut: string; guests: number; notes: string; source: "Airbnb" | "Booking" | "Direta" | "Outro"; portalUrl: string; pinMasked: string; status: string; sent?: boolean; timeline?: string[]; isGuidedDemo?: boolean; demoSessionId?: string; demoCreatedAt?: string };
const reservations: ManualAirbnbReservation[] = [];
const listeners = new Set<() => void>();
const key = (organizationId: string) => `essencialstay:demo:${organizationId}:manual-airbnb-reservations:v1`;
function load(organizationId: string) { if (reservations.some((item) => item.organizationId === organizationId)) return; try { const raw = localStorage.getItem(key(organizationId)); const payload = raw ? JSON.parse(raw) : null; if (payload?.version === 1 && Array.isArray(payload.reservations)) reservations.push(...payload.reservations.filter((item: unknown) => typeof item === "object" && item !== null)); } catch { /* estado demonstrativo vazio */ } }
function save(organizationId: string) { try { localStorage.setItem(key(organizationId), JSON.stringify({ version: 1, reservations: reservations.filter((item) => item.organizationId === organizationId) })); } catch { /* armazenamento opcional */ } }
export function addManualAirbnbReservation(reservation: ManualAirbnbReservation) { load(reservation.organizationId); if (!reservations.some((item) => item.id === reservation.id)) reservations.unshift(reservation); save(reservation.organizationId); listeners.forEach((listener) => listener()); }
export function getManualAirbnbReservations(organizationId?: string) { if (organizationId) load(organizationId); return reservations.filter((item) => item.organizationId === organizationId); }
export function getManualAirbnbReservation(id?: string | null) { return reservations.find((item) => item.id === id) ?? null; }
export function clearManualAirbnbReservations(organizationId: string) { for (let index = reservations.length - 1; index >= 0; index -= 1) if (reservations[index].organizationId === organizationId) reservations.splice(index, 1); try { localStorage.removeItem(key(organizationId)); } catch { /* armazenamento opcional */ } listeners.forEach((listener) => listener()); }
export function getGuidedDemoReservation(organizationId?: string) { return getManualAirbnbReservations(organizationId).find((item) => item.isGuidedDemo) ?? null; }
export function removeManualAirbnbReservation(id: string) { const index = reservations.findIndex((item) => item.id === id); if (index < 0) return; const [removed] = reservations.splice(index, 1); save(removed.organizationId); listeners.forEach((listener) => listener()); }
export function advanceManualAirbnbReservation(id: string) { const sequence = ["Reserva criada", "Experiência enviada", "Check-in pendente", "Check-in realizado", "Hospedado", "Checkout pendente", "Checkout realizado", "Limpeza pendente", "Limpeza concluída", "Quarto disponível"]; const reservation = reservations.find((item) => item.id === id); if (!reservation) return null; const next = sequence[Math.min(sequence.indexOf(reservation.status) + 1, sequence.length - 1)]; reservation.status = next; reservation.timeline = [...(reservation.timeline || ["Reserva criada", "Portal criado", "Concierge criado", "PIN preparado", "QR gerado"]), next]; save(reservation.organizationId); listeners.forEach((listener) => listener()); return reservation; }
export function subscribeManualAirbnbReservations(listener: () => void) { listeners.add(listener); return () => { listeners.delete(listener); }; }
export function getManualCrmGuests(organizationId?: string): GuestProfile[] { return getManualAirbnbReservations(organizationId).map((item) => ({ id: `crm-${item.id}`, name: item.guestName, email: "contato demonstrativo", phone: item.phone.replace(/\d(?=\d{2})/g, "•"), city: "São Paulo, SP", language: "Português", stays: [{ id: item.id, property: "Studio Vila Nova", unit: "Studio Vila Nova", checkIn: item.checkIn, checkOut: item.checkOut, value: 0, reason: "Férias", channel: item.source, status: item.status, services: ["Portal do hóspede", "Concierge digital"] }], segments: ["Airbnb e curta temporada"], preferences: ["A definir na estadia"], marketing: { email: false, whatsapp: false }, opportunity: "Média", digital: ["Portal ativo", "QR Code: gerado", "PIN temporário: ••••••"], notes: "Perfil criado localmente a partir de reserva manual demonstrativa.", campaignHint: "Convidar para avaliar a experiência" })); }
