import { Gift, Search, Send, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { guestCampaigns, getGuestCrmDemo } from "../demo/guest-crm.fixtures";
import { subscribeManualAirbnbReservations } from "../demo/manual-airbnb-reservations";
import type { GuestCampaign, GuestProfile } from "../demo/guest-crm.types";
import { useOrganization } from "../contexts/organization-context";
import { PageHeader } from "../components/layout/page-header";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { DataTable } from "../components/ui/data-table";
import { Input } from "../components/ui/input";
import { Modal } from "../components/ui/modal";
import { Select } from "../components/ui/select";
import { useToast } from "../components/ui/toast";

type Sort = "last" | "stays" | "value" | "name";
const currency = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const initials = (name: string) => name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("");

export function GuestCrmPage() {
  const { organizacaoAtual } = useOrganization(); const { showToast } = useToast();
  const [manualVersion, setManualVersion] = useState(0); useEffect(() => subscribeManualAirbnbReservations(() => setManualVersion((value) => value + 1)), []);
  const guests = useMemo(() => getGuestCrmDemo(organizacaoAtual?.nome_fantasia || organizacaoAtual?.nome, organizacaoAtual?.id), [manualVersion, organizacaoAtual]);
  const [query, setQuery] = useState(""); const [segment, setSegment] = useState(""); const [reason, setReason] = useState(""); const [marketing, setMarketing] = useState(""); const [sort, setSort] = useState<Sort>("last"); const [selected, setSelected] = useState<GuestProfile | null>(null); const [campaign, setCampaign] = useState<GuestCampaign | null>(null); const [coupon, setCoupon] = useState<GuestProfile | null>(null); const [simulated, setSimulated] = useState(false);
  useEffect(() => { setQuery(""); setSegment(""); setReason(""); setMarketing(""); setSelected(null); setCampaign(null); setCoupon(null); }, [organizacaoAtual?.id]);
  const filtered = useMemo(() => guests.filter((guest) => {
    const text = `${guest.name} ${guest.email} ${guest.phone}`.toLowerCase();
    return (!query || text.includes(query.toLowerCase())) && (!segment || guest.segments.includes(segment as never)) && (!reason || guest.stays.some((stay) => stay.reason === reason)) && (!marketing || (marketing === "sim" ? guest.marketing.email || guest.marketing.whatsapp : !guest.marketing.email && !guest.marketing.whatsapp));
  }).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "stays" ? b.stays.length - a.stays.length : sort === "value" ? total(b) - total(a) : last(b).localeCompare(last(a))), [guests, marketing, query, reason, segment, sort]);
  if (!organizacaoAtual || guests.length === 0) return <EmptyGuestCrm />;
  const recurring = guests.filter((guest) => guest.stays.length >= 2).length; const active = guests.filter((guest) => guest.opportunity !== "Sem ação recomendada").length; const opportunities = guests.filter((guest) => guest.opportunity === "Alta").length;
  return <div className="space-y-7"><PageHeader title="Histórico e CRM do Hóspede" description="Conheça o histórico, as preferências e as oportunidades de relacionamento com seus hóspedes." badge="Ambiente demonstrativo" />
    <div className="rounded-lg border border-info/20 bg-info/[0.06] px-4 py-3 text-sm">Ambiente demonstrativo — os dados apresentados são fictícios e não disparam campanhas ou serviços externos.</div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total de hóspedes" value={guests.length} /><Metric label="Hóspedes recorrentes" value={recurring} /><Metric label="Hóspedes ativos" value={active} /><Metric label="Oportunidades de campanha" value={opportunities} /><Metric label="Taxa de recorrência" value={`${Math.round((recurring / guests.length) * 100)}%`} /></section>
    <Card><CardHeader><CardTitle>Oportunidades de relacionamento</CardTitle><CardDescription>Campanhas locais calculadas a partir dos perfis demonstrativos.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{guestCampaigns.map((item) => <button key={item.name} type="button" onClick={() => { setCampaign(item); setSimulated(false); }} className="rounded-md border p-4 text-left hover:bg-secondary/55"><p className="font-medium">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">Público: {item.audience} · {item.discount}% de desconto</p></button>)}</CardContent></Card>
    <Card><CardContent className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-5"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Nome, e-mail ou telefone" /></div><Select value={segment} onChange={(event) => setSegment(event.target.value)}><option value="">Todos os segmentos</option>{segments(guests).map((item) => <option key={item}>{item}</option>)}</Select><Select value={reason} onChange={(event) => setReason(event.target.value)}><option value="">Todos os motivos</option>{reasons(guests).map((item) => <option key={item}>{item}</option>)}</Select><div className="flex gap-2"><Select value={marketing} onChange={(event) => setMarketing(event.target.value)}><option value="">Marketing: todos</option><option value="sim">Aceita marketing</option><option value="nao">Sem consentimento</option></Select><Select value={sort} onChange={(event) => setSort(event.target.value as Sort)}><option value="last">Última estadia</option><option value="stays">Mais estadias</option><option value="value">Maior valor</option><option value="name">Nome</option></Select></div></CardContent></Card>
    <DataTable columns={[{ key: "guest", header: "Hóspede" }, { key: "last", header: "Última hospedagem" }, { key: "stays", header: "Estadias" }, { key: "reason", header: "Motivo" }, { key: "segments", header: "Segmentos" }, { key: "value", header: "Valor acumulado" }, { key: "marketing", header: "Marketing" }, { key: "opportunity", header: "Oportunidade" }, { key: "actions", header: "" }]} rows={filtered.map((guest) => ({ guest: <div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-semibold">{initials(guest.name)}</span><span><span className="block font-medium">{guest.name}</span><span className="block text-xs text-muted-foreground">{guest.email}</span></span></div>, last: formatDate(last(guest)), stays: String(guest.stays.length), reason: guest.stays[0].reason, segments: <div className="flex flex-wrap gap-1">{guest.segments.map((item) => <Badge key={item} variant="outline">{item}</Badge>)}</div>, value: currency(total(guest)), marketing: <Badge variant={guest.marketing.email || guest.marketing.whatsapp ? "success" : "muted"}>{guest.marketing.email || guest.marketing.whatsapp ? "Consentimento" : "Sem consentimento"}</Badge>, opportunity: <Badge variant={guest.opportunity === "Alta" ? "highlight" : guest.opportunity === "Média" ? "warning" : "muted"}>{guest.opportunity}</Badge>, actions: <div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => setSelected(guest)}>Ver histórico</Button><Button size="sm" variant="ghost" onClick={() => { setCampaign(guestCampaigns[0]); setSimulated(false); }}>Campanha</Button><Button size="sm" variant="ghost" onClick={() => setCoupon(guest)}>Cupom</Button></div> }))} />
    <p className="text-xs text-muted-foreground">Campanhas somente podem ser enviadas a contatos com base legal ou consentimento válido.</p>
    <ProfileModal guest={selected} onClose={() => setSelected(null)} /><CampaignModal campaign={campaign} simulated={simulated} onClose={() => setCampaign(null)} onSimulate={() => { setSimulated(true); showToast("Simulação concluída. Nenhuma mensagem foi enviada."); }} /><CouponModal guest={coupon} organization={organizacaoAtual.nome_fantasia || organizacaoAtual.nome} onClose={() => setCoupon(null)} />
  </div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <Card><CardContent className="p-4"><p className="text-2xl font-semibold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
function EmptyGuestCrm() { return <div className="space-y-6"><PageHeader title="Histórico e CRM do Hóspede" description="Conheça o histórico, as preferências e as oportunidades de relacionamento com seus hóspedes." /><Card><CardContent className="p-10 text-center"><UsersRound className="mx-auto size-8 text-muted-foreground" /><h2 className="mt-4 font-semibold">Ainda não existem hóspedes no histórico.</h2><p className="mt-2 text-sm text-muted-foreground">Os perfis serão criados a partir das reservas e hospedagens integradas à Essencial Stay.</p><div className="mt-5 flex justify-center gap-2"><Button variant="outline" onClick={() => window.location.assign("/integracoes")}>Ver integrações</Button><Button variant="outline" onClick={() => window.location.assign("/reservas")}>Ver reservas</Button></div></CardContent></Card></div>; }
function ProfileModal({ guest, onClose }: { guest: GuestProfile | null; onClose: () => void }) { if (!guest) return null; return <Modal open title={`Histórico · ${guest.name}`} description="Perfil demonstrativo com informações internas e dados mascarados." onClose={onClose} size="large"><div className="space-y-6"><section className="grid gap-3 sm:grid-cols-2"><Info label="Contato" value={`${guest.email} · ${guest.phone}`} /><Info label="Cidade e idioma" value={`${guest.city} · ${guest.language}`} /><Info label="Estadias" value={`${guest.stays.length} · ticket médio ${currency(total(guest) / guest.stays.length)}`} /><Info label="Valor acumulado" value={currency(total(guest))} /></section><Section title="Histórico de hospedagens">{guest.stays.map((stay) => <div key={stay.id} className="border-l-2 border-accent pl-3"><p className="font-medium">{stay.property} · {stay.unit}</p><p className="text-sm text-muted-foreground">{formatDate(stay.checkIn)} · {stay.reason} · {currency(stay.value)} · {stay.channel}</p><p className="text-xs text-muted-foreground">{stay.services.join(" · ") || "Sem serviços adicionais"}</p></div>)}</Section><Section title="Preferências">{guest.preferences.map((item) => <Badge key={item} variant="outline">{item}</Badge>)}</Section><Section title="Experiência digital">{guest.digital.map((item) => <div key={item} className="text-sm">{item}</div>)}</Section><Section title="CRM e marketing"><p className="text-sm">E-mail: {guest.marketing.email ? "consentimento demonstrativo" : "não autorizado"} · WhatsApp: {guest.marketing.whatsapp ? "consentimento demonstrativo" : "não autorizado"}</p><p className="mt-1 text-sm text-muted-foreground">Próxima ação: {guest.campaignHint}</p></Section><Section title="Observações internas"><p className="text-sm text-muted-foreground">{guest.notes}</p></Section></div></Modal>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h3 className="mb-3 font-semibold">{title}</h3><div className="flex flex-wrap gap-2 rounded-md bg-surface p-4">{children}</div></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-md border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }
function CampaignModal({ campaign, simulated, onClose, onSimulate }: { campaign: GuestCampaign | null; simulated: boolean; onClose: () => void; onSimulate: () => void }) { if (!campaign) return null; return <Modal open title={campaign.name} description="Campanha demonstrativa. Nenhuma integração externa será acionada." onClose={onClose}><div className="space-y-4 text-sm"><Info label="Público estimado" value={campaign.audience} /><Info label="Canal e validade" value={`${campaign.channel} · ${campaign.validity}`} /><Info label="Assunto" value={campaign.subject} /><p>{campaign.message}</p><Badge variant="highlight">Desconto demonstrativo: {campaign.discount}%</Badge>{simulated && <p className="rounded-md bg-success/[0.1] p-3 text-success">Simulação concluída. Nenhuma mensagem foi enviada.</p>}<Button onClick={onSimulate}><Send className="size-4" />Simular envio</Button></div></Modal>; }
function CouponModal({ guest, organization, onClose }: { guest: GuestProfile | null; organization: string; onClose: () => void }) { if (!guest) return null; const code = `${organization.replace(/[^a-z]/gi, "").slice(0, 6).toUpperCase()}15`; return <Modal open title="Cupom demonstrativo" description="Não possui validade comercial." onClose={onClose}><div className="space-y-4"><Info label="Campanha" value={guest.campaignHint} /><Info label="Público" value={guest.segments.join(", ")} /><Info label="Validade" value="31/12/2026" /><div className="rounded-md border border-dashed p-5 text-center"><Gift className="mx-auto size-6 text-accent" /><p className="mt-2 text-2xl font-bold tracking-widest">{code || "CRM15"}</p><p className="mt-1 text-xs text-muted-foreground">15% de desconto · cupom fictício</p></div></div></Modal>; }
function total(guest: GuestProfile) { return guest.stays.reduce((sum, stay) => sum + stay.value, 0); } function last(guest: GuestProfile) { const values = guest.stays.map((stay) => stay.checkIn).sort(); return values[values.length - 1] ?? ""; } function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(`${value}T12:00:00`)); } function segments(guests: GuestProfile[]) { return [...new Set(guests.flatMap((guest) => guest.segments))]; } function reasons(guests: GuestProfile[]) { return [...new Set(guests.flatMap((guest) => guest.stays.map((stay) => stay.reason)))]; }
