import { Check, ChevronLeft, ChevronRight, Hotel, Play, Presentation, Sparkles } from "lucide-react";
import { useState, type ReactNode } from "react";
import { completeDemoHotelCleaning, completeDemoHotelJourney, goToDemoHotelStep, requestDemoHotelCleaning, startDemoHotelCleaning, startDemoHotelJourney, type DemoHotelJourney } from "../../demo/demo-hotel-guided-journey";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Modal } from "../ui/modal";

const steps = ["Reserva recebida", "Preparação", "Check-in", "Durante a estadia", "Checkout", "Limpeza", "CRM"];
type Props = { open: boolean; journey: DemoHotelJourney; onClose: () => void; onChange: (journey: DemoHotelJourney) => void; };

export function DemoHotelGuidedDemo({ open, journey, onClose, onChange }: Props) {
  const [presentationMode, setPresentationMode] = useState(false);
  const started = journey.status !== "not_started";
  const move = (step: number) => onChange(goToDemoHotelStep(journey, step));
  const next = () => move(journey.currentStep + 1);
  const title = !started ? "Demonstração do Hotel Summit Monaco" : `Etapa ${journey.currentStep} de 7 · ${steps[journey.currentStep - 1]}`;
  return <Modal open={open} title={title} description={!started ? "Vamos simular toda a jornada de um hóspede no Essencial Stay." : "Ambiente demonstrativo — nenhuma integração, mensagem ou dispositivo real é acionado."} onClose={onClose} size="large">
    {!started ? <Intro onStart={() => onChange(startDemoHotelJourney(journey))} onClose={onClose} /> : <div className={presentationMode ? "space-y-7 text-base" : "space-y-6"}>
      <div className="flex flex-wrap items-center gap-2"><Badge variant="highlight">AMBIENTE DEMONSTRATIVO</Badge><Button size="sm" variant="ghost" className="ml-auto" onClick={() => setPresentationMode((value) => !value)}><Presentation className="size-4" />{presentationMode ? "Modo padrão" : "Modo apresentação"}</Button></div>
      <ol className="grid grid-cols-7 gap-1" aria-label="Etapas da demonstração">{steps.map((label, index) => <li key={label} className="min-w-0"><span className={`block h-1.5 rounded-full ${index + 1 <= journey.currentStep ? "bg-accent" : "bg-secondary"}`} /><span className="mt-1 hidden text-[10px] text-muted-foreground md:block">{index + 1}. {label}</span></li>)}</ol>
      <StepContent journey={journey} onChange={onChange} onNext={next} />
      <div className="flex justify-between border-t pt-5"><Button variant="ghost" disabled={journey.currentStep === 1} onClick={() => move(journey.currentStep - 1)}><ChevronLeft className="size-4" />Voltar</Button>{journey.currentStep < 7 && journey.currentStep !== 4 && journey.currentStep !== 6 && <Button variant="accent" onClick={next}>Continuar<ChevronRight className="size-4" /></Button>}</div>
    </div>}
  </Modal>;
}

function Intro({ onStart, onClose }: { onStart: () => void; onClose: () => void }) { return <div className="space-y-6"><div className="rounded-lg border border-accent/20 bg-accent/[0.07] p-5"><Hotel className="size-7 text-accent" /><p className="mt-3 text-sm leading-6">Apresente a jornada completa do hóspede, desde a reserva recebida pelo PMS até o relacionamento pós-hospedagem.</p></div><ol className="grid gap-2 text-sm sm:grid-cols-2">{["Reserva recebida pelo PMS", "Preparação automática da hospedagem", "Check-in e experiência do hóspede", "Serviços durante a estadia", "Checkout e limpeza", "CRM e relacionamento"].map((item, index) => <li key={item} className="flex gap-2"><span className="font-semibold text-accent">{index + 1}.</span>{item}</li>)}</ol><p className="text-xs text-muted-foreground">Todos os dados desta jornada são fictícios e não acionam serviços externos.</p><div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancelar</Button><Button variant="accent" onClick={onStart}><Play className="size-4" />Começar demonstração</Button></div></div>; }

function StepContent({ journey, onChange, onNext }: { journey: DemoHotelJourney; onChange: (journey: DemoHotelJourney) => void; onNext: () => void }) {
  const reservation = journey.reservation;
  if (journey.currentStep === 1) return <Step title="Reserva recebida automaticamente" text="O PMS simulado enviou uma nova hospedagem para o Essencial Stay." benefit="Elimina digitação manual, reduz erros e inicia a preparação da hospedagem."><Details journey={journey} /><Button variant="accent" onClick={onNext}>Ver hospedagem<ChevronRight className="size-4" /></Button></Step>;
  if (journey.currentStep === 2) return <Step title="Hospedagem preparada automaticamente" text="A jornada já está pronta antes da chegada do hóspede." benefit="Reduz trabalho da recepção, padroniza a preparação e evita esquecimentos."><Checklist items={["Reserva confirmada", "Unidade identificada", "Jornada do hóspede criada", "Portal do hóspede preparado", "Comunicação simulada preparada", "Automação simulada preparada", "Acesso demonstrativo preparado"]} /><Button variant="accent" onClick={onNext}>Continuar para o check-in<ChevronRight className="size-4" /></Button></Step>;
  if (journey.currentStep === 3) return <Step title="Experiência digital pronta" text="Claudio Demonstração encontra todas as informações da estadia em um único lugar." benefit="Reduz dúvidas, melhora o check-in e diminui chamadas para a recepção."><div className="rounded-lg border bg-surface p-4 text-sm"><p className="font-semibold">Portal do hóspede · {reservation.unit}</p><p className="mt-2 text-muted-foreground">Wi-Fi, informações do hotel, acesso demonstrativo, serviços e automação simulada.</p><p className="mt-2">Check-in: <span className="font-medium">Concluído na simulação</span></p></div><Button variant="accent" onClick={onNext}>Continuar<ChevronRight className="size-4" /></Button></Step>;
  if (journey.currentStep === 4) return <Step title="Serviços durante a hospedagem" text="O hóspede pode solicitar ajuda diretamente pela experiência digital." benefit="Organiza solicitações e reduz a comunicação informal."><div className="rounded-lg border bg-surface p-4 text-sm"><p className="font-medium">Solicitação de limpeza · {reservation.unit}</p><p className="mt-1 text-muted-foreground">Origem: Portal do Hóspede · {journey.cleaningStatus === "nao_solicitada" ? "Aguardando solicitação" : "Solicitação recebida"}</p></div>{journey.cleaningStatus === "nao_solicitada" ? <Button variant="accent" onClick={() => onChange(requestDemoHotelCleaning(journey))}>Solicitar limpeza</Button> : <Button variant="accent" onClick={onNext}>Realizar checkout<ChevronRight className="size-4" /></Button>}</Step>;
  if (journey.currentStep === 5) return <Step title="Checkout concluído" text="A unidade deixou de estar ocupada e a governança foi notificada." benefit="Agiliza a liberação do quarto e integra recepção e governança."><Checklist items={["Checkout registrado", "Acesso demonstrativo encerrado", "Unidade aguardando limpeza", "Governança notificada", "CRM atualizado"]} /><Button variant="accent" onClick={onNext}>Ver tarefa de limpeza<ChevronRight className="size-4" /></Button></Step>;
  if (journey.currentStep === 6) return <Step title="Quarto preparado para o próximo hóspede" text="A tarefa demonstrativa acompanha a Suíte 809 até sua liberação." benefit="Dá visibilidade operacional e aumenta a agilidade para uma nova venda."><div className="rounded-lg border bg-surface p-4 text-sm"><p className="font-medium">Limpeza · Suíte 809</p><p className="mt-1 text-muted-foreground">Status: {journey.cleaningStatus === "em_andamento" ? "Em limpeza" : journey.cleaningStatus === "concluida" ? "Limpeza concluída · unidade disponível" : "Aguardando limpeza"}</p></div>{journey.cleaningStatus === "solicitada" ? <Button variant="accent" onClick={() => onChange(startDemoHotelCleaning(journey))}>Iniciar limpeza</Button> : journey.cleaningStatus === "em_andamento" ? <Button variant="accent" onClick={() => onChange(completeDemoHotelCleaning(journey))}>Concluir limpeza</Button> : <Button variant="accent" onClick={onNext}>Continuar para o CRM<ChevronRight className="size-4" /></Button>}</Step>;
  return <Step title="Relacionamento após a hospedagem" text="O histórico demonstrativo de Claudio Demonstração foi atualizado." benefit="Apoia fidelização, campanhas futuras e novas oportunidades comerciais."><div className="rounded-lg border bg-surface p-4 text-sm"><p className="font-medium">Hospedagem concluída · R$ 890,00 (fictício)</p><p className="mt-1 text-muted-foreground">Preferência: quarto silencioso · Próxima ação: enviar benefício para uma próxima hospedagem.</p></div><Button variant="accent" onClick={() => onChange(completeDemoHotelJourney(journey))}><Sparkles className="size-4" />Concluir demonstração</Button>{journey.status === "completed" && <div className="rounded-lg border border-success/30 bg-success/[0.08] p-4"><p className="font-semibold">Demonstração concluída</p><p className="mt-1 text-sm text-muted-foreground">O Essencial Stay acompanhou toda a jornada do hóspede, da reserva ao relacionamento pós-estadia.</p></div>}</Step>;
}

function Step({ title, text, benefit, children }: { title: string; text: string; benefit: string; children: ReactNode }) { return <section className="space-y-4"><div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div>{children}<p className="rounded-md bg-secondary/70 p-3 text-sm"><span className="font-semibold">Benefício para o hotel: </span>{benefit}</p></section>; }
function Details({ journey }: { journey: DemoHotelJourney }) { const { guest, reservation } = journey; return <dl className="grid gap-3 rounded-lg border bg-surface p-4 text-sm sm:grid-cols-2"><Info label="Hóspede" value={guest.name} /><Info label="Código" value={reservation.code} /><Info label="Unidade" value={reservation.unit} /><Info label="Canal" value={reservation.channel} /><Info label="Check-in" value={reservation.checkIn} /><Info label="Checkout" value={reservation.checkOut} /><Info label="Status" value="Recebida" /></dl>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function Checklist({ items }: { items: string[] }) { return <div className="grid gap-2 sm:grid-cols-2">{items.map((item) => <div key={item} className="flex items-center gap-2 rounded-md border p-3 text-sm"><Check className="size-4 text-success" />{item}</div>)}</div>; }
