import { ChevronDown, ChevronUp, Play, X } from "lucide-react";
import { useState } from "react";
import type { ManualAirbnbReservation } from "../../demo/manual-airbnb-reservations";
import { Button } from "../ui/button";
import { useNavigate } from "react-router-dom";
import { useToast } from "../ui/toast";
import { advanceManualAirbnbReservation } from "../../demo/manual-airbnb-reservations";

const guide: Record<string, { step: number; title: string; text: string; action: string }> = { "Reserva criada": { step: 1, title: "Reserva rápida", text: "A reserva foi criada e a experiência digital já está pronta.", action: "Preparar mensagem" }, "Experiência enviada": { step: 2, title: "Portal do hóspede", text: "Agora mostre como o hóspede recebe o acesso.", action: "Abrir Portal" }, "Check-in pendente": { step: 3, title: "Check-in digital", text: "Explique como funciona o check-in digital.", action: "Preparar Check-in" }, "Check-in realizado": { step: 4, title: "Check-in confirmado", text: "Mostre a confirmação da chegada.", action: "Iniciar Hospedagem" }, "Hospedado": { step: 5, title: "Hospedagem", text: "Mostre a hospedagem em andamento.", action: "Iniciar Checkout" }, "Checkout pendente": { step: 6, title: "Checkout", text: "Apresente o encerramento da estadia.", action: "Ir para Checkout" }, "Checkout realizado": { step: 7, title: "Limpeza", text: "Explique a preparação da unidade.", action: "Enviar para Limpeza" }, "Limpeza pendente": { step: 7, title: "Limpeza", text: "Explique a preparação da unidade.", action: "Finalizar Limpeza" }, "Limpeza concluída": { step: 7, title: "Unidade preparada", text: "A unidade está pronta para liberação.", action: "Liberar Unidade" }, "Quarto disponível": { step: 8, title: "Histórico e CRM", text: "Finalize mostrando o histórico do hóspede.", action: "Abrir Histórico" } };
export function GuidedDemoPanel({ reservation, onUpdate, onOpenCheckin, onOpenCheckout }: { reservation: ManualAirbnbReservation; onUpdate: () => void; onOpenCheckin: () => void; onOpenCheckout: () => void }) { const [closed, setClosed] = useState(false); const [minimized, setMinimized] = useState(false); const [portalShown, setPortalShown] = useState(false); const navigate = useNavigate(); const { showToast } = useToast(); const item = guide[reservation.status] || guide["Reserva criada"]; function act() { if (reservation.status === "Check-in pendente") return onOpenCheckin(); if (reservation.status === "Checkout pendente") return onOpenCheckout(); if (reservation.status === "Experiência enviada" && !portalShown) { window.open(reservation.portalUrl, "_blank", "noopener,noreferrer"); setPortalShown(true); showToast("Portal aberto."); return; } if (reservation.status === "Quarto disponível") { navigate("/hospedes"); return; } advanceManualAirbnbReservation(reservation.id); onUpdate(); showToast(`${item.action} demonstrado.`); } const label = reservation.status === "Experiência enviada" && portalShown ? "Preparar Check-in" : item.action; if (closed) return <Button className="fixed bottom-4 right-4 z-40" size="sm" onClick={() => { setClosed(false); showToast("Demonstração retomada."); }} aria-label="Retomar demonstração"><Play className="size-4" />Retomar Demonstração</Button>; return <aside className="fixed bottom-4 right-4 z-40 w-[min(24rem,calc(100vw-2rem))] rounded-xl border bg-card p-4 shadow-floating" aria-label="Guia da demonstração"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">▶ Demonstração Essencial Stay</p><p className="mt-1 text-xs text-muted-foreground">Etapa {item.step} de 8</p></div><div className="flex"><Button size="icon" variant="ghost" aria-label={minimized ? "Expandir painel" : "Minimizar painel"} onClick={() => setMinimized((value) => !value)}>{minimized ? <ChevronUp className="size-4" /> : <ChevronDown className="size-4" />}</Button><Button size="icon" variant="ghost" aria-label="Pausar demonstração" onClick={() => { setClosed(true); showToast("Demonstração pausada."); }}><X className="size-4" /></Button></div></div>{!minimized && <><div className="mt-3 h-1.5 rounded bg-secondary"><div className="h-full rounded bg-accent" style={{ width: `${(item.step / 8) * 100}%` }} /></div><h2 className="mt-4 font-medium">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.text}</p><Button className="mt-4 w-full" variant="outline" onClick={act}>{label}</Button></>}</aside>; }
